name: On Deployment Created
on: 
  deployment
env:
  PULL_NUMBER: ${{ github.event.deployment.payload.pr }}
  MICRO_SERVICE: ${{ github.event.deployment.payload.microservice }}
  DEPLOY_REF: ${{ github.event.deployment.ref }}
  DEPLOYMENT_ID: ${{ github.event.deployment.id }}
  ENVIRONMENT: ${{ github.event.deployment.environment }}
  INFRA_NAME: devhub-app-web
  SUFFIX: "-${{ github.event.deployment.payload.pr }}"
jobs:
  
  build:
    if: ${{ github.event.deployment.payload.microservice == 'web' }}
    name: Build Gatsby App
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      
      - name: Change Deploy Status to Pending
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            github.repos.createDeploymentStatus({
              deployment_id: context.payload.deployment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'pending'
            });
      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL}}
          parameters: '{"apitoken": "${{ secrets.SA_PASSWORD }}"}'
          cmd: |
            'version'
      - name: Cancel previous builds (if any)
        run: 'oc cancel-build -n ${{ secrets.TOOLS_NAMESPACE }} bc/${{ env.INFRA_NAME }}${{ env.SUFFIX }} || echo no build found for ${{ github.event.deployment.payload.pr }}'
      - name: Check if should run build (based on a commit id comparison)
        env:
          TOOLS_NAMESPACE: ${{ secrets.TOOLS_NAMESPACE }}
        # reference https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: |
          _commit=$(.github/helpers/get_last_build_commit_id.sh)
          echo "::set-env name=BUILD_COMMIT_ID::$_commit"
      - name: Create Build
        env:
          TOOLS_NAMESPACE: ${{ secrets.TOOLS_NAMESPACE }}
          GATSBY_MATOMO_URL: ${{ secrets.GATSBY_MATOMO_URL }}
          GATSBY_MATOMO_SITE_URL: ${{ secrets.GATSBY_MATOMO_SITE_URL }}
          GATSBY_MATOMO_SITE_ID: ${{ secrets.GATSBY_MATOMO_SITE_ID }}

        run: |
          oc process -f openshift/templates/web/bc.yaml -n $TOOLS_NAMESPACE \
          -p SUFFIX=$SUFFIX \
          -p SOURCE_REPOSITORY_URL="https://github.com/$GITHUB_REPOSITORY" \
          -p SOURCE_REPOSITORY_REF=$GITHUB_REF \
          -p MATOMO_URL=$GATSBY_MATOMO_URL \
          -p NAME=$INFRA_NAME \
          -p MATOMO_SITE_URL=$GATSBY_MATOMO_SITE_URL \
          -p MATOMO_SITE_ID=$GATSBY_MATOMO_SITE_ID -n $TOOLS_NAMESPACE \
          -p VERSION="$PULL_NUMBER" | \
          oc apply -n $TOOLS_NAMESPACE -f -
          
      - name: Start Build (if needed)
        if: contains(env.BUILD_COMMIT_ID, github.sha)
        env:
          TOOLS_NAMESPACE: ${{ secrets.TOOLS_NAMESPACE }}
        run: |
          echo "Build started"
          oc start-build -n $TOOLS_NAMESPACE $INFRA_NAME$SUFFIX --wait
  deploy:
    if: ${{ github.event.deployment.payload.microservice == 'web' }}
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - name: Run Deployment to Dev
        env:
          DEV_NAMESPACE: ${{ secrets.DEV_NAMESPACE }}
          TOOLS_NAMESPACE: ${{ secrets.TOOLS_NAMESPACE }}
          GATSBY_MATOMO_URL: ${{ secrets.GATSBY_MATOMO_URL }}
          GATSBY_MATOMO_SITE_URL: ${{ secrets.GATSBY_MATOMO_SITE_URL }}
          GATSBY_MATOMO_SITE_ID: ${{ secrets.GATSBY_MATOMO_SITE_ID }}
          SSO_DEV_URL: ${{ secrets.SSO_DEV_URL }}
          SSO_CLIENT_ID: "devhub-web-$PULLNUMBER"
          SSO_REALM_NAME: ${{ secrets.SSO_REALM_NAME }}
          MATOMO_URL: ${{ secrets.MATOMO_URL }}
          ALGOLIA_INDEX_NAME_SUFFIX: "-build-$PULL_NUMBER"
        run: |
          oc process -f openshift/templates/web/dc.yaml -n $DEV_NAMESAPCE \
          -p NAME=$INFRA_NAME \
          -p IMAGE_NAMESPACE=$TOOLS_NAMESPACE \
          -p IMAGE_TAG="$PULL_NUMBER" \
          -p SUFFIX=$SUFFIX \
          -p SOURCE_REPOSITORY_URL="https://github.com/$GITHUB_REPOSITORY" \
          -p SOURCE_REPOSITORY_REF=$GITHUB_REF \
          -p SEARCH_GATE_API_URL="https://searchgate.pathfinder.gov.bc.ca" \
          -p SSO_BASE_URL="$SSO_DEV_URL" \
          -p DEVHUB_API_URL="https://devhub-api-prod-devhub-prod.pathfinder.gov.bc.ca" \
          -p SSO_CLIENT_ID="$SSO_CLIENT_ID" \
          -p SSO_REALM_NAME="$SSO_REALM_NAME" \
          -p ALGOLIA_INDEX_NAME_SUFFIX="$ALGOLIA_INDEX_NAME_SUFFIX" | \
          oc apply -n $DEV_NAMESAPCE -f -
          echo "Deployment started"