apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: devhub-app-web-bc-template
labels:
  template: devhub-app-web
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}-static
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: ${NAME}-static${SUFFIX}
    name: ${NAME}-static${SUFFIX}
  spec:
    runPolicy: SerialLatestOnly
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-static:${VERSION}
    postCommit: {}
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 400m
        memory: 750Mi
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: 'app-web'
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
                      # very important to increase nodes default memory limit to handle
                      # all the pages gatsby creates
        - name: NODE_OPTIONS
          value: --max_old_space_size=1000
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: devhub-gh-token
              key: GITHUB_TOKEN
        - name: GATSBY_ALGOLIA_APP_ID
          valueFrom:
            secretKeyRef:
              name: devhub-algolia-build
              key: GATSBY_ALGOLIA_APP_ID
        - name: ALGOLIA_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: devhub-algolia-build
              key: ALGOLIA_ADMIN_KEY
        - name: GATSBY_ALGOLIA_SEARCH_KEY
          valueFrom:
            secretKeyRef:
              name: devhub-algolia-build
              key: GATSBY_ALGOLIA_SEARCH_KEY
        - name: GATSBY_ALGOLIA_INDEX_NAME_SUFFIX
          value: ${SUFFIX}
        - name: MEETUP_API_KEY
          valueFrom: 
            secretKeyRef:
              name: devhub-meetup-token
              key: MEETUP_API_KEY
        - name: EVENT_BRITE_API_KEY
          valueFrom:
            secretKeyRef:
              name: devhub-eventbrite-token
              key: EVENT_BRITE_API_KEY
        - name: MATOMO_API_KEY
          valueFrom:
            secretKeyRef:
              name: matomo-api-key
              key: MATOMO_API_KEY
        - name: GATSBY_MATOMO_URL
          value: ${MATOMO_URL}
        - name: GATSBY_MATOMO_SITE_URL
          value: ${MATOMO_SITE_URL}
        - name: GATSBY_MATOMO_SITE_ID
          value: ${MATOMO_SITE_ID}
        from:
          kind: ImageStreamTag
          name: caddy-s2i-builder:latest
        incremental: false
      type: Source
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: ${NAME}-static:${VERSION}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: devhub-app-web
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: SOURCE_REPOSITORY_URL
  displayName: SOURCE_REPOSITORY_URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/devhub-app-web.git
- description: SOURCE_REPOSITORY_REF
  displayName: SOURCE_REPOSITORY_REF
  name: SOURCE_REPOSITORY_REF
  required: true
  value: ''
- description: Location of the Matomo server that the app should post events to.
  displayName: Matomo URL
  name: MATOMO_URL
  required: false
  value: ''
- description: URL (route) where this app is deployed
  displayName: Matomo URL
  name: MATOMO_SITE_URL
  required: false
  value: ''
- description: Identifier for this site within Matomo
  displayName: Matomo URL
  name: MATOMO_SITE_ID
  required: false
  value: '1'
